version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
    ports:
      - 5433:5432
    hostname: postgres_aws
    restart: always
    volumes:
      - postgres_data_aws:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: django:latest
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - .:/code
      - static_volume:/usr/share/nginx/html/static
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/usr/share/nginx/html/static
    depends_on:
      - app

volumes:
  postgres_data_aws:
  static_volume: